name: Release

run-name: Release (${{ github.event.head_commit.message }})

on:
  push:
    branches: [main]

env:
  CI: true
  DO_NOT_TRACK: 1

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Version and Publish
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'chore: version packages')"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Cache Turbo
        uses: actions/cache@v5
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Mise
        uses: jdx/mise-action@v4

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Create Release or Version PR
        uses: changesets/action@v1
        with:
          version: bun run changeset:version
          publish: bun run changeset:publish

          commit: "chore: version packages"
          title: Version packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
